spring.datasource.url=jdbc:mysql://localhost:3306/bugtracker?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=@Rajesh5630
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

jwt.secret=94a08da1fecbb6e8b46990538c7b50b294a08da1fecbb6e8b46990538c7b50b2
jwt.expirationMs=86400000
